version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "9292:9292"
    environment:
      RACK_ENV: production
      BD_Username: user
      BD_Password: password
      BD_Port: 5432
      BD_pool: 1
    depends_on:
      - db

  db:
   image: postgres:14.1-alpine
   restart: unless-stopped
   expose: ["5432"]
   environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
   ports:
      - "5432:5432"