version: "3.8"

networks:
  smm-network:

services:
  oauth2_service:
    container_name: oauth2_service
    build:
      context: ./oauth2_service
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0
    env_file:
      - .env
      - oauth.env
    networks:
      smm-network:
    ports:
      - ${OAUTH2_SERVICE_PORT}:8000
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  smm_service:
    container_name: smm_service
    build:
      context: ./smm_service
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0
    env_file:
      - .env
      - smm.env
    networks:
      smm-network:
    ports:
      - ${SMM_SERVICE_PORT}:8000
    depends_on:
      - oauth2_service
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3