services:
  tacos:
    build: src/
    restart: unless-stopped
    env_file:
      - path: ./.env
    ports:
      - "1488:1488"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
  db:
    build: db/
    restart: unless-stopped
    env_file:
      - path: ./.env
    volumes:
      - postgres:/data/postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
    healthcheck:
      test: ["CMD", "psql", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
  cleaner:
    build: src/cleaner/
    restart: unless-stopped
    env_file:
      - path: ./.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M

networks:
  tacos: {}

volumes:
    postgres: {}
