name: nessat
services:
  server:
    build: .
    ports:
      - "7576:7576"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 1000M
    environment:
      FLAG: "mctf{fake_flag}"
