services:
  front:
    image: nginx:1.26-alpine
    restart: unless-stopped
    ports:
      - "9898:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/html/static
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    depends_on:
      - mongodb
      - worker
    environment:
      - CACHE_ENABLED=1
    cpus: 2
    mem_limit: 512m
    pids_limit: 512
  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    command: ['php', 'artisan', 'queue:work', '--tries=1']
    cpus: 1
    pids_limit: 512
    mem_limit: 256m
  schedule:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    command: ['php', 'artisan', 'schedule:work']
    cpus: 0.5
    pids_limit: 128
    mem_limit: 128m        
  mongodb:
    image: mongo:4.4.6
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    mem_limit: 512M
volumes:
  db-data: