name: 'dnser'

services:
  app:
    tty: true
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/tmp/dnser/
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dnsdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

volumes:
  pgdata:
    driver: local
