from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df3f46b543e4'
down_revision = '2ff7ad14c403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_profile_id'], ['id'])
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reactions_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reactions_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('reactions_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_type', postgresql.ENUM('user', 'post', 'comment', name='targettarget'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_profile_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
