version: '3.8'

services:
  web:
    image: nginx:1.27.2-alpine
    volumes:
    - ./binaries.zip:/var/www/html/binaries.zip
    - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - ${PORT}:80